#!/bin/bash
USER=root
sudo rm agents.db
sudo venv/bin/python3 db_create.py
sudo chown http:http agents.db
sudo chmod 666 agents.db
cd loot
rm agent* -rf
cd ..
sudo systemctl restart myproject.service
sudo chown http:http server.sock
sudo systemctl restart nginx.service
